# Generated by Django 6.0.4 on 2026-05-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='is_corret',
            field=models.BooleanField(default=False),
        ),
    ]
